




#Rodar threshould de pesos
#
GCC=g++

INCLUDE_DIR= -I/usr/local/include/opencv4 -L/usr/local/lib
LIBS =  -lopencv_highgui -lopencv_core -lopencv_imgproc -lboost_system  -lcrypto -lssl -lpthread
FLAGS = -O3 -std=c++14

all:
	
	$(GCC) generate_vector_python.cpp -o generate_vector_python mcc_vector/mcc.cpp $(INCLUDE_DIR) $(LIBS) $(FLAGS)   





#Rodar threshould de pesos
#
